apps/logreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout'),
    
    url(r'^process/(?P<form_type>\w+)$', views.process, name='process'),
    
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new, name='new'),
    url(r'^edit/(?P<user_id>\d*$)', views.edit, name='edit'),
    # url(r'^update/(?P<user_id>\d+)/(?P<ud_type>\w+)$', views.update, name='update'),
    url(r'^show/(?P<user_id>\d+)', views.show, name='show'),
    url(r'^delete/(?P<user_id>\d+)', views.delete, name='delete'),
    url(r'^add_message/(?P<to_user_id>\d+)', views.add_message, name='add_message'),
]

dashboard/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # |^login$|^register$|^process-login$|^process-registration$
    url(r'^', include('apps.logreg.urls', namespace='logreg')),
    url(r'^dashboard/', include('apps.dash.urls', namespace='dash')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
]

apps/users/models.py
import bcrypt
import re
from django.db import models


class User(models.Model):
    first_name = models.CharField(max_length = 20)
    last_name = models.CharField(max_length = 20)
    email = models.CharField(max_length=20)
    password_plaintext = models.CharField(max_length=32, null=True)
    password = models.CharField(max_length=255, null=False)
    pw_salt = models.CharField(max_length=255)
    is_admin = models.BooleanField()
    description = models.TextField(max_length=500)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name+' '+self.last_name

    def encrypt_pw(self):
        self.pw_salt = bcrypt.gensalt()
        self.password = bcrypt.hashpw(self.password_plaintext.encode(), self.pw_salt)
        self.password_plaintext = None

    def login(self):
        db_user = User.objects.filter(email=self.email)
        errors = []
        if len(db_user)==0:
            db_user = self
            errors.append('No user exists with this email address')
        else:
            db_user = db_user[0]
            check_password = bcrypt.hashpw(self.password_plaintext.encode(), db_user.pw_salt.encode()).decode()
            if check_password != db_user.password:
                errors.append('Incorrect password supplied for this user')

        return db_user, errors 

    def valid_info(self):
        errors = []
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
        if not EMAIL_REGEX.match(self.email):
            errors.append('Invalid email format.')

        if len(self.first_name) <= 1:
            errors.append('First name too short')
        if len(self.last_name) <= 1:
            errors.append('Last name too short')

        return errors

    def valid_pw(self):
        errors = []
        if len(self.password_plaintext) < 8:
            errors.append('Password must be at least 8 characters')
        
        return errors 

    def register(self):
        errors = []

        # look up if email exists already
        db_user = User.objects.filter(email=self.email)
        
        if len(db_user) > 0:
            errors.append('User already exists with this email')
    
        errors += self.valid_info()
        errors += self.valid_pw()

        return self, errors

    def edit_info(self):
        errors = self.valid_info()

        return self, errors

    def edit_pw(self):
        errors = self.valid_pw()
        return self, errors

class Message(models.Model):
    to_user = models.ForeignKey(User, related_name="messages_received")
    from_user = models.ForeignKey(User, related_name="messages_written")
    content = models.TextField(max_length=400)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    message = models.ForeignKey(Message)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User
from .models import Message
import logging

from dashboard.settings import SERVER_LOG


"""

logger = logging.getLogger('server')
logger.debug("Logging started for %s" % (SERVER_LOG))
hdlr = logging.FileHandler(SERVER_LOG)
formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
hdlr.setFormatter(formatter)
logger.addHandler(hdlr) 
"""

def is_logged_in(request):
    return request.session.get('logged_id', False)

def is_admin(request):
    return request.session.get('is_admin', False)

def index(request):
    if is_logged_in(request):
        return redirect('dash:home')
    else:
        return redirect('logreg:login')

def show(request, user_id):
    user = User.objects.get(id=user_id)
    return render(request, 'users/show.html', {'user': user, 'is_admin': is_admin(request)})

def edit(request, user_id=None):
    print(SERVER_LOG)
    SERVER_LOG.debug('we find ourselves in the edit function')
    if request.method == 'GET':
        # show the edit page if it's a GET request
        if user_id:
            if not is_admin(request):
                return redirect('dash:home')
            
            user = User.objects.filter(id=user_id)
            if len(user) == 0:
                return redirect('dash:home')
            else:
                user = user[0]
        else:
            user = User.objects.get(id=request.session['user_id'])

        profile = user.id == request.session['user_id']
        context = {
            'user': user, 
            'is_admin': is_admin(request), # if theyre an admin, can change other's info
            'profile': profile # if theyre editing their own profile, then they can edit the description
            }
        return render(request, 'users/edit.html', context)

    elif request.method == 'POST':
        # posting to this route handles editing the user
        SERVER_LOG.debug('we got data!')
        SERVER_LOG.debug(request.POST)
        user = User.objects.filter(id=user_id)
        if len(user) == 0:
            return redirect('dash:home')
        user = user[0]
        
        if 'password' in request.POST:
            # editing password
            user.password_plaintext = request.POST['password']
            user, errors = user.edit_pw()

            if request.POST['password'] != request.POST['password2']:
                errors.append('Passwords do not match')

            if len(errors) == 0:
                user.encrypt_pw()
                user.save()
                messages.success(request, 'User password has been updated.')
        else:
            # editing non-password fields
            user.first_name = request.POST.get('first_name', user.first_name)
            user.last_name = request.POST.get('last_name', user.last_name)
            user.email = request.POST.get('email', user.email)
            user.is_admin = bool(int(request.POST.get('is_admin', user.is_admin)))
            user.description = request.POST.get('description', user.description)
        
            user, errors = user.edit_info()        

            if len(errors) == 0:
                user.save()
                request.session['is_admin'] = user.is_admin
                
                
                messages.success(request, 'User info updated.')
        
        if len(errors) > 0:
            for err_msg in errors:
                messages.error(request, err_msg, extra_tags='danger')
        return redirect('users:edit', user_id)


def delete(request, user_id):
    user = User.objects.get(id=user_id)
    user.delete()
    return redirect('dash:home')

def new(request):
    return render(request, 'users/new.html', {'is_admin': is_admin(request)})

def add_message(request, to_user_id):
    if request.method=='GET':
        return redirect('dash:home')

    from_user_id = request.session['user_id']
    
    content = request.POST['content']
    if len(content) > 0:
        new_message= Message.objects.create(
            from_user = User.objects.get(id=from_user_id),
            to_user = User.objects.get(id=to_user_id),
            content = content
        )
    return redirect('users:show', to_user_id)

apps/users/templates/users/edit.html
{% extends "dash/default.html" %}

{% block title %}Edit User{% endblock %}


<!-- Bootstrap theme CSS -->
{% block css %}
    {% load staticfiles %}
    <link href="{% static 'users/css/jumbotron.css' %}" rel="stylesheet">
{% endblock %}


{% block sidebar %}
    <!-- override sidebar -->
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
        <h1>{{user}}</h1>
        <p>
            {% if profile %}
                <form action="{% url 'users:edit' user.id  %}" method="POST">
                    {% csrf_token %}
                    <textarea name="description" class="edit" type="text" cols=50>{{user.description}}</textarea><br>
                    <input type="submit" value="Update Description" class="btn btn-default">
                </form>
            {% else %}
                {{user.description}}
            {% endif %}

        </p>
        
        <!--<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>-->
        </div>
    </div>
    

    <!--<div class="container">
        <p>User ID #{{user.id}}</p>
        <p>Joined on {{user.created_at}}</p>
        <p>Email address: {{user.email}}</p>
    </div>-->

    <div class="container">
        <div class="row placeholders">
            {% for message in messages %}
                <p class="alert alert-{{message.tags}} alert-dismissible"> {{message}}</p>
                <!-- dismissible feature not working, I think requires another library -->
            {% endfor %}
        </div>

        
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-6">
            <h2>Edit Personal Info</h2>
            <form action="{% url 'users:edit' user.id %}" method="POST">
            {% csrf_token %}
            <p>First Name</p>
            <p><input type="text" name="first_name" value="{{user.first_name}}"></p>

            <p>Last Name</p>
            <p><input type="text" name="last_name" value="{{user.last_name}}"></p>

            <p>Email</p>
            <p><input type="text" name="email" value="{{user.email}}"></p>
            
            {% if is_admin %}
            <p>Change admin status:
                <input type="radio" name="is_admin" value="1" {% if user.is_admin %}checked{% endif %}> Admin &nbsp;
                <input type="radio" name="is_admin" value="0" {% if not user.is_admin %}checked{% endif %}> Normal User
                <!--<input type="checkbox" name="is_admin" value="True" >-->
            </p>
            {% endif %}

            <p><input type="submit" value="Update Info" class="btn btn-default"></p>
        </form>
        </div>

        <div class="col-md-5">
            <h2>Edit Password</h2>
            <form action="{% url 'users:edit' user.id %}" method="POST">
                {% csrf_token %}
                <p>Password</p>
                <p><input type="password" name="password"></p>
                <p>Confirm Password</p>
                <p><input type="password" name="password2"></p>
            
                <p><input type="submit" value="Update Password" class="btn btn-default"></p>
            </form>
        </div>

    
   
{% endblock %}

apps/users/templates/users/new.html
{% extends "logreg/default.html" %}

{% block title %}New User{% endblock %}

{% block formtitle %}Enter new user information{% endblock %}


{% block header %}

    {% include 'dash/header.html' %}

{% endblock %}


{% block form %}
    <form action="{% url 'logreg:process' 'create' %}" method="POST">
        {% csrf_token %}
        <label for="first_name">First Name</label>
        <input type="text" name="first_name">

        <label for="last_name">Last Name</label>
        <input type="text" name="last_name">

        <label for="email">Email</label>
        <input type="text" name="email">

        <label for="password">Password</label>
        <input type="password" name="password">
        <label for="password2">Confirm Password</label>
        <input type="password" name="password2">

        <label for="is_admin">Make admin?</label>
        <input type="radio" name="is_admin" value="1"> Yes &nbsp;
        <input type="radio" name="is_admin" value="0"> No

        <input type="submit" value="Create User" class="btn btn-lg btn-success">
    </form>

{% endblock %}

apps/users/templates/users/show.html
{% extends "dash/default.html" %}

{% block title %}Show User{% endblock %}

<!-- Bootstrap theme CSS -->
{% block css %}
    {% load staticfiles %}
    <link href="{% static 'users/css/jumbotron.css' %}" rel="stylesheet">
{% endblock %}

{% block sidebar %}
    <!-- override sidebar -->
{% endblock %}

{% block content %}
    <div class="jumbotron">
      <div class="container">
        <h1>{{user}}</h1>
        <p>{{user.description}}</p>
        
        <!--<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>-->
      </div>
    </div>

    <div class="container">
        <p>User ID #{{user.id}}</p>
        <p>Joined on {{user.created_at}}</p>
        <p>Email address: {{user.email}}</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>Leave a message for {{user.first_name}}</h2>
                <form action="{% url 'users:add_message' user.id %}" method="POST">
                    {% csrf_token %}
                    <textarea name="content" rows="4" cols="60"></textarea><br>
                    <input type="submit" value="Post Message" class="btn btn-primary btn-lg">
                </form>
            </div>
        </div>
        <h2>{{user.first_name}}'s Inbox</h2>
        {% for message in user.messages_received.all %}
        <div class="row">
            <div class="col-md-4">
            <h4><a href="{% url 'users:show' message.from_user.id %}">{{message.from_user}}</a> wrote:</h4>
            <p>{{message.content}}</p>
            <p>{{message.created_at}}</p>
            </div>
            
        </div>
        {% empty %}
        <p>No messages yet. Leave a message above!</p>
        {% endfor %}
    </div>

    

{% endblock %}