apps/dash/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='home'),
    # url(r'^admin$', views.admin, name='admin')
]

apps/logreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout'),
    
    url(r'^process/(?P<form_type>\w+)$', views.process, name='process'),
    
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new, name='new'),
    url(r'^edit/(?P<user_id>\d*$)', views.edit, name='edit'),
    # url(r'^update/(?P<user_id>\d+)/(?P<ud_type>\w+)$', views.update, name='update'),
    url(r'^show/(?P<user_id>\d+)', views.show, name='show'),
    url(r'^delete/(?P<user_id>\d+)', views.delete, name='delete'),
    url(r'^add_message/(?P<to_user_id>\d+)', views.add_message, name='add_message'),
]

dashboard/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # |^login$|^register$|^process-login$|^process-registration$
    url(r'^', include('apps.logreg.urls', namespace='logreg')),
    url(r'^dashboard/', include('apps.dash.urls', namespace='dash')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
]

apps/dash/models.py
from django.db import models

# Create your models here.

apps/dash/views.py
from django.shortcuts import render, redirect
from ..users.models import User 

def is_logged_in(request):
    return request.session.get('logged_in', False)

def is_admin(request):
    return request.session.get('is_admin', False)

def index(request):
    if is_logged_in(request):
        
        context = {
            'users': User.objects.all(),
            'is_admin': is_admin(request)
        }
        return render(request, 'dash/index.html', context)
        """
        if not context['is_admin']:
            
            return render(request, 'dash/index.html', context)
        else:
            return redirect('dash:admin', context)
        """
    else:
        return redirect('logreg:login')
    
"""
def admin(request):
    if is_admin(request):
        context = {
                'users': User.objects.all(),
                'is_admin': True
            }
        return render(request, 'dash/index.html', context)
    else:
        return redirect('dash:index')
"""

apps/dash/templates/dash/default.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{%block title %}{% endblock %}</title>


    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    
    {% block css %}
       
    {% endblock %}

    <!-- FontAwesome -->
    <script src="https://use.fontawesome.com/e5e7825618.js"></script>

    {% block jquery %}
    
    {% endblock %}
</head>
<body>
    
    {% include 'dash/header.html' %}
    

    <div class="container-fluid">
        {% block sidebar %}
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                
                <ul class="nav nav-sidebar">
                    {% if is_admin %}
                        <li><a href="{% url 'users:new' %}">Create a New User</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        {% endblock %}
        {% block content %}
         
        {% endblock %}

    </div>

</body>
</html>

apps/dash/templates/dash/header.html
<header style="height:3em">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand">
                Welcome {{request.session.first_name}}!
                {% if is_admin %}<i class="fa fa-key" aria-hidden="true"></i>{% endif %}
            </span>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'dash:home' %}">Dashboard</a></li>
                <!--<li><a href="#">Settings</a></li>-->
                <li><a href="{% url 'users:edit' '' %}">Profile</a></li>
                <li><a href="{% url 'logreg:logout' %}">Logout</a></li>
            </ul>
            <!--<form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>-->
            </div>
        </div>
    </nav>
    <!--
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" value="Log Out">
            </form>-->

</header>

apps/dash/templates/dash/index.html
{% extends 'dash/default.html' %}

{% block title %}User Dashboard{% endblock %}

{% block css %}
<!-- Bootstrap theme CSS -->
    {% load staticfiles %}
    <link href="{% static 'dash/css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
   
{% block jquery %}
<script>
    $(document).ready(function(){
        $('.delete').click(function(e){
            ok = confirm('Are you sure you would like to delete this user?');
            console.log(ok);
            if(!ok){
                e.preventDefault();
            }
            //
            // TODO lol this doesnt work!
        })
    })
</script>
{% endblock %}

<body>
    <header>
        
    </header>
    <div class="container-fluid">
        
        {% block content %}
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Users</h1>

                <div class="row placeholders">
                    {% for message in messages %}
                        <p class="alert alert-{{message.tags}} alert-dismissible"> {{message}}</p>
                        <!-- dismissible feature not working, I think requires another library -->
                    {% endfor %}
                </div>

                
                    <div class="table-responsive">
                        <table class="table table-striped">
                        <thead>
                            <th>ID</th> <th>Name</th> <th>Email</th> <th>Created At</th> <th>Last Updated</th>
                            {% if request.session.is_admin %}<th>Actions</th>{% endif %}
                        </thead>
                        <tbody>
                            {% for user in users %}
                                <tr>
                                    <td>{{user.id}}</td> 
                                    <td>
                                        <a href="{% url 'users:show' user.id %}">{{user}}</a>
                                        {% if user.is_admin %}<i class="fa fa-key" aria-hidden="true"></i>{% endif %}
                                    </td> 
                                    <td>{{user.email}}</td> 
                                    <td>{{user.created_at}}</td>
                                    <td>{{user.updated_at}}</td>
                                    {% if request.session.is_admin %}
                                    <td>
                                        <a href="{% url 'users:edit' user.id %}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                        {% if user.id != request.session.user_id %}
                                            <a class="delete" href="{% url 'users:delete' user.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                                        {% endif %}
                                    </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </div>
        {% endblock %}

    </div>

</body>
</html>